name: release-docker
on:
  workflow_dispatch:
    inputs:
      version:
        description: "release version/tag"
        required: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - uses: actions/checkout@v4
        with:
          path: siyuan-note

      - name: Clone origin and apply patches
        run: |
          git config --global core.autocrlf false
          cd ${{ github.workspace }}/siyuan-note/
          git clone --branch ${{ github.event.inputs.version }} --depth=1 https://github.com/siyuan-note/siyuan.git
          cd siyuan

          git apply ${{ github.workspace }}/siyuan-note/patches/siyuan/disable-update.patch
          git apply ${{ github.workspace }}/siyuan-note/patches/siyuan/default-config.patch
          git apply ${{ github.workspace }}/siyuan-note/patches/siyuan/mock-vip-user.patch

          git status

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

      - name: Build and push Docker image
        working-directory: ${{ github.workspace }}/siyuan-note/siyuan
        run: |
          docker buildx build \
            --push \
            --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKER_HUB_USER }}/siyuan:latest \
            -t ${{ secrets.DOCKER_HUB_USER }}/siyuan:${{ github.event.inputs.version }} \
            .
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}