name: release-pc

on:
  workflow_dispatch:
    inputs:
      version:
        description: "release version/tag"
        required: true
      packageManager:
        description: "pnpm@x.x.x"
        required: true

jobs:
  check_release:
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.check.outputs.should_build }}
      version_number: ${{ steps.format_version.outputs.version }}
    steps:
      - name: Format version number
        id: format_version
        run: |
          VERSION="${{ github.event.inputs.version }}"
          # Remove 'v' prefix if present
          VERSION="${VERSION#v}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Check if release assets exist
        id: check
        uses: joutvhu/get-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
        continue-on-error: true

  build:
    needs: check_release
    if: needs.check_release.outputs.should_build != 'false'
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-22.04
            kernel_path: "../app/kernel-linux/SiYuan-Kernel"
            build_args: "-s -w -X github.com/siyuan-note/siyuan/kernel/util.Mode=prod"
            electron_args: "dist-linux"
            goos: "linux"
            goarch: "amd64"
            suffix: "linux.tar.gz"
          - os: macos-latest
            kernel_path: "../app/kernel-darwin/SiYuan-Kernel"
            build_args: "-s -w -X github.com/siyuan-note/siyuan/kernel/util.Mode=prod"
            electron_args: "dist-darwin"
            goos: "darwin"
            goarch: "amd64"
            suffix: "mac.dmg"
          - os: macos-latest
            kernel_path: "../app/kernel-darwin-arm64/SiYuan-Kernel"
            build_args: "-s -w -X github.com/siyuan-note/siyuan/kernel/util.Mode=prod"
            electron_args: "dist-darwin-arm64"
            goos: "darwin"
            goarch: "arm64"
            suffix: "mac-arm64.dmg"
          - os: windows-2019
            kernel_path: "../app/kernel/SiYuan-Kernel.exe"
            build_args: "-s -w -H=windowsgui -X github.com/siyuan-note/siyuan/kernel/util.Mode=prod"
            electron_args: "dist"
            goos: "windows"
            gobin: "bin"
            mingwsys: "MINGW64"
            goarch: "amd64"
            suffix: "win.exe"

    steps:
      - name: Check if asset exists
        id: check_asset
        uses: joutvhu/get-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
        continue-on-error: true

      - name: Check if need to build
        id: should_build
        run: |
          ASSET_NAME="siyuan-${{ github.event.inputs.version }}-${{ matrix.config.suffix }}"
          if [[ "${{ steps.check_asset.outputs.assets }}" == *"$ASSET_NAME"* ]]; then
            echo "Asset $ASSET_NAME already exists, skipping build"
            echo "build=false" >> $GITHUB_OUTPUT
          else
            echo "Asset $ASSET_NAME not found, proceeding with build"
            echo "build=true" >> $GITHUB_OUTPUT
          fi

      - uses: actions/checkout@v4
        if: steps.should_build.outputs.build == 'true'
        with:
          path: siyuan-note

      - name: clone origin and apply patches
        if: steps.should_build.outputs.build == 'true'
        run: |
          mkdir -p ${{ github.workspace }}/go
          cd ${{ github.workspace }}/siyuan-note/

          git clone --branch ${{ github.event.inputs.version }} --depth=1 https://github.com/siyuan-note/siyuan.git
          cd siyuan

          git apply ${{ github.workspace }}/siyuan-note/patches/siyuan/disable-update.patch
          git apply ${{ github.workspace }}/siyuan-note/patches/siyuan/default-config.patch
          git apply ${{ github.workspace }}/siyuan-note/patches/siyuan/mock-vip-user.patch

          git status

      - name: Set up MingGW
        if: steps.should_build.outputs.build == 'true' && contains(matrix.config.goos, 'windows')
        uses: msys2/setup-msys2@v2
        with:
          install: p7zip mingw-w64-x86_64-lua

      - name: Set up TDM-GCC
        if: steps.should_build.outputs.build == 'true' && contains(matrix.config.goarch, '386')
        run: msys2 -c "bash siyuan-note/siyuan/scripts/get-tdm-gcc.sh tdm https://github.com/jmeubank/tdm-gcc/releases/download/v10.3.0-tdm-1/tdm-gcc-10.3.0.exe" && echo "CC=${{ github.workspace }}/tdm/bin/gcc.exe" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        working-directory: ${{ github.workspace }}

      - name: Set up Go
        if: steps.should_build.outputs.build == 'true'
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ github.workspace }}/siyuan-note/siyuan/kernel/go.mod
          cache-dependency-path: "**/*.sum"
      
      - run: go version
        if: steps.should_build.outputs.build == 'true'

      - name: Set up goversioninfo
        if: steps.should_build.outputs.build == 'true' && contains(matrix.config.goos, 'windows')
        run: go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo && go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo
        working-directory: ${{ github.workspace }}/siyuan-note/siyuan/kernel
        env:
          GO111MODULE: on
          CGO_ENABLED: 1
          GOOS: ${{ matrix.config.goos }}
          GOPATH: ${{ github.workspace }}/go
          GOARCH: ${{ matrix.config.goarch }}

      - name: Set up Node
        if: steps.should_build.outputs.build == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node pnpm
        if: steps.should_build.outputs.build == 'true'
        run: npm install -g ${{ github.event.inputs.packageManager }}
        working-directory: ${{ github.workspace }}/siyuan-note/siyuan/app

      - name: Install Node Dependencies
        if: steps.should_build.outputs.build == 'true'
        run: pnpm install --no-frozen-lockfile
        working-directory: ${{ github.workspace }}/siyuan-note/siyuan/app

      - name: Building UI
        if: steps.should_build.outputs.build == 'true'
        run: pnpm run build
        working-directory: ${{ github.workspace }}/siyuan-note/siyuan/app

      - name: Generate Icon Resource and Properties/Version Info For Windows
        if: steps.should_build.outputs.build == 'true' && contains(matrix.config.goos, 'windows')
        run: ${{ github.workspace }}\go\${{ matrix.config.gobin }}\goversioninfo -platform-specific=true -icon="resource\icon.ico" -manifest="resource\goversioninfo.exe.manifest"
        working-directory: ${{ github.workspace }}/siyuan-note/siyuan/kernel

      - name: Building Kernel
        if: steps.should_build.outputs.build == 'true'
        run: go build --tags fts5 -o "${{ matrix.config.kernel_path }}" -v -ldflags "${{ matrix.config.build_args }}"
        working-directory: ${{ github.workspace }}/siyuan-note/siyuan/kernel
        env:
          GO111MODULE: on
          CGO_ENABLED: 1
          GOOS: ${{ matrix.config.goos }}
          GOPATH: ${{ github.workspace }}/go
          GOARCH: ${{ matrix.config.goarch }}

      - name: Building Electron
        if: steps.should_build.outputs.build == 'true'
        run: pnpm run ${{ matrix.config.electron_args }}
        working-directory: ${{ github.workspace }}/siyuan-note/siyuan/app

      - name: Create DEB Package
        if: steps.should_build.outputs.build == 'true' && matrix.config.goos == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot dpkg-dev imagemagick
          
          # Create directory structure for deb package
          mkdir -p siyuan-deb/DEBIAN
          mkdir -p siyuan-deb/usr/lib/siyuan
          mkdir -p siyuan-deb/usr/share/applications
          mkdir -p siyuan-deb/usr/share/icons/hicolor/512x512/apps
          
          # Copy application files
          cp -r ${{ github.workspace }}/siyuan-note/siyuan/app/build/linux-unpacked/* siyuan-deb/usr/lib/siyuan/
          
          # Create desktop entry
          cat > siyuan-deb/usr/share/applications/siyuan.desktop << EOF
          [Desktop Entry]
          Name=SiYuan
          Comment=A personal knowledge management system
          Exec=/usr/lib/siyuan/siyuan
          Icon=siyuan
          Terminal=false
          Type=Application
          Categories=Office;
          EOF
          
          # Download and convert icon
          wget https://raw.githubusercontent.com/siyuan-note/siyuan/refs/heads/master/kernel/resource/icon.ico -O siyuan.ico
          convert siyuan.ico[0] -resize 512x512 siyuan-deb/usr/share/icons/hicolor/512x512/apps/siyuan.png
          
          # Create control file
          cat > siyuan-deb/DEBIAN/control << EOF
          Package: siyuan
          Version: ${{ needs.check_release.outputs.version_number }}
          Section: office
          Priority: optional
          Architecture: amd64
          Maintainer: melashri <siyuan@elashri.com>
          Description: SiYuan Note-Taking Software
           SiYuan is a personal knowledge management system that supports 
           building a personal knowledge base.
          EOF
          
          # Build deb package
          fakeroot dpkg-deb --build siyuan-deb
          mv siyuan-deb.deb siyuan-${{ github.event.inputs.version }}-amd64.deb

      - uses: joutvhu/get-release@v1
        if: steps.should_build.outputs.build == 'true'
        id: get_current_release
        with:
          tag_name: ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Electron App
        if: steps.should_build.outputs.build == 'true'
        uses: shogo82148/actions-upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_current_release.outputs.upload_url }}
          asset_name: siyuan-${{ github.event.inputs.version }}-${{ matrix.config.suffix }}
          asset_path: ${{ github.workspace }}/siyuan-note/siyuan/app/build/siyuan-*-${{ matrix.config.suffix }}
          asset_content_type: application/octet-stream

      - name: Upload DEB Package
        if: steps.should_build.outputs.build == 'true' && matrix.config.goos == 'linux'
        uses: shogo82148/actions-upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_current_release.outputs.upload_url }}
          asset_name: siyuan-${{ github.event.inputs.version }}-amd64.deb
          asset_path: ${{ github.workspace }}/siyuan-${{ github.event.inputs.version }}-amd64.deb
          asset_content_type: application/vnd.debian.binary-package
